name: Dotnet Package Publishing

jobs:
  dotnet-sdk-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: sudo apt-get install jq    

    - name: Generate Sdk
      run: curl -L -X POST "https://www.apimatic.io/api/api-entities/{{Api Entity Id}}/code-generations" -H "Accept: application/json" -H "Authorization: X-Auth-Key {{Api Key}}" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "Template=CS_NET_STANDARD_LIB" -o generation.json

    - name: Parse Generation Json
      run: echo '::set-output name=codegenId::'$(jq -r '.id' generation.json)

    - name: Download Sdk
      run: curl -L -X GET "https://www.apimatic.io/api/api-entities/{{Api Entity Id}}/code-generations/${{ steps.parse_output.outputs.codegenId }}/generated-sdk" -o dotnet-sdk.zip

    - name: Unzip Sdk
      run: unzip dotnet-sdk.zip -d dotnet-sdk

    