name: Dotnet Package Publishing

on: workflow_dispatch

jobs:
  dotnet-sdk-publish:
    runs-on: ubuntu-latest

    env:
      api-key: YXBpbWF0aWNfNjMzMjkxZTkzMjY0NDcxYzYyY2RhYWFk
      api-entity-id: hePvp4tDl-HP0IBVGI650qHJ0EDCTuGWt49Qcv7yqkwsKpspojKfhSbtkK3eT_xJ

    steps:
    - name: Install jq
      run: sudo apt-get install jq    

    - name: Generate Sdk
      run: curl -L -X POST "https://www.apimatic.io/api/api-entities/$api-entity-id/code-generations" -H "Accept:application/json" -H "Authorization:X-Auth-Key $api-key" -H "Content-Type:application/x-www-form-urlencoded" --data-urlencode "Template=CS_NET_STANDARD_LIB" -o generation.json

    - name: Parse Generation Json
      run: echo '::set-output name=codegenId::'$(jq -r '.id' generation.json)

    - name: Download Sdk
      run: curl -L -X GET "https://www.apimatic.io/api/api-entities/$api-entity-id/code-generations/${{ steps.parse_output.outputs.codegenId }}/generated-sdk" -o dotnet-sdk.zip
    
    - name: List files
      run: ls

    - name: Check zip
      run: cat generation.json

    - name: Unzip Sdk
      run: unzip dotnet-sdk
